spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?serverTimezone=CTT&characterEncoding=UTF-8
    username: duolaharry
    password: Wangchongyu123
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 20
    min-idle: 10
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8

mvc:
  date-format: yyyy-mm-dd

mybatis:
  mapper-locations: classpath:dataImpl/*/*Mapper.xml
